### ISSUE TITLE
Question..about the plugin

### ISSUE THREAD

**Issue by MikkelDK** [Birk3n/TS3Spotify#10]
Hi,

Is it possible for "clients" can get bot log in on their own Spotify account (to the BOT)?

**Comment by Birk3n** [comment]
Hi Mikkel, 
when there is no running spotify session the bot looks for the account of the user who requests something. After that the spotify session is created and is closed after !stop oder disconnect. When the requesting user has no account linked the bot doesnt do anything.

**Comment by MikkelDK** [comment]
Hi @Birk3n 

Thanks for the information.
Do you have a nice how-install?

Can it be used on this ts3audiobot version: 0.12.0-alpha.52 🙏

**Comment by Birk3n** [comment]
Hi, 
unfortunately there is no nice or easy way to install it.

Which Version of .net is your bot running on? 
Keep the other dll's in the lib folder of your build.

**Comment by MikkelDK** [comment]
> Which Version of .net is your bot running on?

None, I did just launching with ./TS3AudioBot. - Do I need to use the dotnet version before it will work?
> Keep the other dll's in the lib folder of your build.

Which DLL files need to keep in the "lib" folder?
I did this now:
![](https://pic.lindhost.eu/filezilla_TUxZY2lkq5.png)

**Comment by MikkelDK** [comment]
//closed didn't get this to work.
