### ISSUE TITLE
|ERR|SpotifyPlugin.dll (Error)

### ISSUE THREAD

**Issue by dyb00** [Birk3n/TS3Spotify#4]
Hey, 

I'm running TS3AudioBot on a Debian 10 machine and wanted to add the Spotify Plugin.

I just compiled the code and copied SpotifyPlugin.dll + lib with librespot to TS3AudioBot plugins folder. 
But loading the plugin results in an error. 

> 
> ERROR|0|Plugin.InitializeAssembly InitializeAssembly failed: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> 
>  System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
>  
>  File name: 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ---> System.IO.FileNotFoundException: Could not load the specified file.
>  File name: 'System.Runtime'
>     at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
>     at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
>     at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
>     at System.Reflection.RuntimeAssembly.GetExportedTypes()
>     at TS3AudioBot.Plugins.Plugin.InitializeAssembly(Assembly assembly) in C:\projects\ts3audiobot\TS3AudioBot\Plugins\Plugin.cs:line 255
> 

Is there any advice?

**Comment by Birk3n** [comment]
Did you build it with dotnetcore?

**Comment by dyb00** [comment]
I built with `dotnet build `

Now I tried `dotnet build --framework netcoreapp3.1 --configuration Release TS3SpotifyPlugin` which leads to the same result. 

My installed .NET applications are:

```
dotnet --list-sdks
2.2.402 [/usr/share/dotnet/sdk]
3.1.302 [/usr/share/dotnet/sdk]
```
```
dotnet --list-runtimes
Microsoft.AspNetCore.All 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
Microsoft.AspNetCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 2.2.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by dyb00** [comment]
Small update: 

I got the plugin working when I changed 
`<TargetFramework>netcoreapp3.1</TargetFramework>`
to
`<TargetFramework>netcoreapp2.2</TargetFramework>`
in the .csproj file. 

Now it struggles with saving login credencials due to permissions. I'll look into it over the next few days:

> 2020-08-05 | INFO|0|Bot.OnMessageReceived User --- requested: !spotify account add
> 2020-08-05 |FATAL|0|Core.ExceptionHandler Critical program failure!
> System.ComponentModel.Win32Exception (13): Permission denied
>    at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
>    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
>    at System.Diagnostics.Process.Start()
>    at SpotifyCommand.SpotifyInstance.startProcess() in C:\Users\Hans\Downloads\TS3Spotify-master\TS3Spotify-master\TS3SpotifyPlugin\PluginFiles\SpotifyCommand.cs:line 727
>    at SpotifyCommand.LoginStepFour(SpotifyAccount account, ClientCall invoker, String password) in C:\Users\Hans\Downloads\TS3Spotify-master\TS3Spotify-master\TS3SpotifyPlugin\PluginFiles\SpotifyCommand.cs:line 230
>    at SpotifyCommand.<>c__DisplayClass42_0.<LoginStepThree>g__handler|0(Object sender, TextMessage textMessage) in C:\Users\Hans\Downloads\TS3Spotify-master\TS3Spotify-master\TS3SpotifyPlugin\PluginFiles\SpotifyCommand.cs:line 216
>    at TS3AudioBot.Ts3Client.ExtendedTextMessage(Object sender, TextMessage textMessage) in C:\projects\ts3audiobot\TS3AudioBot\Ts3Client.cs:line 650
>    at TSLib.Full.TsFullClient.InvokeEvent(LazyNotification lazyNotification) in C:\projects\ts3audiobot\TSLib\Full\TsFullClient.gen.cs:line 1099
>    at TSLib.ExtraThreadEventDispatcher.DispatchLoop() in C:\projects\ts3audiobot\TSLib\EventDispatcher.cs:line 80
>    at System.Threading.Thread.ThreadMain_ThreadStart()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by dyb00** [comment]
Have found out that the plugin stores the login data in the lib folder. You have to set the appropriate rights, otherwise the plugin cannot write the file and the TS3AudioBot gets a fatal error and crashes. 

Now I have the problem to connect the plugin to Spotify. I run the` !spotify account add` routine and insert the Auth-token from the URL bar into TeamSpeak (the stuff between` ?code=` and `&state=`). But at the end I get the feedback: 

> Something went wrong check your Auth-Token.

**Comment by dyb00** [comment]
I got it running after I updated the Spotify lib files to version 5.1.1 and customized it in the program.

**Comment by dyb00** [comment]
Sure, 

just edit following lines in SpotifyPlugin.csproj to:

```
    <PackageReference Include="SpotifyAPI.Web" Version="5.1.1" />
    <PackageReference Include="SpotifyAPI.Web.Auth" Version="5.1.1" />
```

and replace SpotifyAPI.Web.Auth.dll + SpotifyAPI.Web.Auth.dll in the lib folder with version 5.1.1. from https://www.nuget.org/packages/SpotifyAPI.Web.Auth/

**Comment by Errorismx** [comment]
![image](https://user-images.githubusercontent.com/67753731/91047925-0e950300-e645-11ea-9b3c-bbf26b660668.png)
![image](https://user-images.githubusercontent.com/67753731/91047939-148ae400-e645-11ea-89a8-daa43412e00b.png)

**Comment by Errorismx** [comment]
What did u put on the redirect link?
