### ISSUE TITLE
Plugin got error 

### ISSUE THREAD

**Issue by Errorismx** [Birk3n/TS3Spotify#5]
17:08:20.6567| WARN|0| InitializeAssembly failed, The file "SpotifyPlugin.dll" seems to be missing some dependecies (Method 'get_Length' in type 'SpotifyStreamAudioProducer' from assembly 'SpotifyPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.)

![image](https://user-images.githubusercontent.com/67753731/90975994-7a9f3a80-e563-11ea-89ad-ffcd88f64ab3.png)

**Comment by dyb00** [comment]
What does the TS3AudioBot.log say?

**Comment by Errorismx** [comment]
[ts3audiobot_2020-08-23_18_00_28.log](https://github.com/Birk3n/TS3Spotify/files/5117919/ts3audiobot_2020-08-23_18_00_28.log)

**Comment by dyb00** [comment]
> Version: 0.12.0-alpha.51/develop/2cae1819

Maybe there is an incompatibility with alpha version of AudioBot. I'm running 0.11.3-stable

**Comment by Errorismx** [comment]
![image](https://user-images.githubusercontent.com/67753731/91120247-6e2ff480-e6bf-11ea-9fa7-d48f97563775.png)
still get an error bro

**Comment by dyb00** [comment]
But that is another error and the same I had. You can look up in my issue how I solved this:

> I got the plugin working when I changed
> `<TargetFramework>netcoreapp3.1</TargetFramework>`
> to
> `<TargetFramework>netcoreapp2.2</TargetFramework>`
> in the .csproj file.

**Comment by Errorismx** [comment]
I cant compile if i change that to version 2.2
![image](https://user-images.githubusercontent.com/67753731/91165732-60986000-e6fb-11ea-8eb2-61dbb53f4493.png)

**Comment by dyb00** [comment]
Because you want to compile to an old version of TS3AudioBot.

Replace content of TS3AudioBot with https://github.com/Birk3n/TS3Spotify/tree/master in you projects/compiling folder.

**Comment by Errorismx** [comment]
already done that becasue im using git clone --recurse-submodules https://github.com/Birk3n/TS3Spotify.git

**Comment by dyb00** [comment]
But are these the same files you use to compile the spotify plugin? If you clone spotify plugin, it's linking to an old commit.
![grafik](https://user-images.githubusercontent.com/69061774/91172858-2f109c00-e6dd-11ea-8e7a-07909587173c.png)


TS3AudioBot compiles flawlessly. The TS3AudioBot.csproj in TS3Spotify-master\TS3AudioBot\TS3AudioBot contains

   ` <TargetFrameworks>net472;netcoreapp2.2;netcoreapp3.1;netstandard2.0</TargetFrameworks>`

which should work with netcoreapp2.2

**Comment by Errorismx** [comment]
still doesn't work can u PS into this github so i will follow your solution

**Comment by dyb00** [comment]
My bad. I linked you the wrong git: https://github.com/Splamy/TS3AudioBot/tree/master

**Comment by Errorismx** [comment]
![image](https://user-images.githubusercontent.com/67753731/91175521-2636bf00-e70b-11ea-8324-0680c5a28ad3.png)
still got this error
![image](https://user-images.githubusercontent.com/67753731/91175556-3189ea80-e70b-11ea-843e-51ea272c0de2.png)

**Comment by dyb00** [comment]
> 
> 
> still doesn't work can u PS into this github so i will follow your solution

Since I have the TS3AudioBot running on a Debian server, I use the netcore2.2 dll to run the bot. 

Do you use the .exe to start the AudioBot? Then try `<TargetFramework>net472</TargetFramework>` in the SpotifyPlugin.csproj.

**Comment by Errorismx** [comment]
It seem like have to run it with debian. Thx man!
