### ISSUE TITLE
Ich bekomm das plugin nicht installiert

### ISSUE THREAD

**Issue by McGamerComunity** [Birk3n/TS3Spotify#9]
ich weiß nicht ob du mir dabei helfen kannst aber ich hab folgendes problem
wenn ich das plugin compile und in den pluginsordner packe kommt der fehler in der console

19:53:41.1563| INFO|2| User SnapixLP requested: !plugins list
19:53:41.2274|ERROR|2| InitializeAssembly failed: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not resolve type with token 01000010 from typeref (expected class 'TS3AudioBot.Plugins.ITabPlugin' in assembly 'TS3AudioBot, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')
Could not resolve type with token 0100004e from typeref (expected class 'TS3AudioBot.Audio.IPlayerSource' in assembly 'TS3AudioBot, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null')

**Comment by McGamerComunity** [comment]
hab mal versucht die datein aus dem lib ordner auch in den plugins zu packen da ich die erste issue gelesen hab hat auch nicht geklappt
da kommt dann der fehler
20:00:28.0254| INFO|2| User SnapixLP requested: !plugins list
20:00:28.0386| WARN|2| Any source or binary plugin file must contain at least one plugin or factory. ("SpotifyAPI.Web.dll (Unknown)")
20:00:28.0724| WARN|2| Any source or binary plugin file must contain at least one plugin or factory. ("NAudio.dll (Unknown)")
20:00:28.0770|ERROR|2| InitializeAssembly failed: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
Could not load file or assembly 'Unosquare.Labs.EmbedIO, Version=2.9.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

**Comment by McGamerComunity** [comment]
hab grad mal noch ein paar andere sachen probiert aber mir fehlen die ideen was ich noch versuchen kann
hättest du villeicht mal zeit bei mir aufm teamspeak vorbeizuschauen und mit dort villeicht zu helfen
die tsdaten wären dafür: onyxnet.de

**Comment by Birk3n** [comment]
Ich versuch morgen/übermorgen mal ins TS zu kommen..

**Comment by McGamerComunity** [comment]
danke dir

**Comment by McGamerComunity** [comment]
wenn du morgen zeit hast da könnt ich gegen 13/14 uhr und montag erst ab 18/19 uhr
